on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run read-yaml action
        id: using
        uses: ./
        with:
          file: './action.yml'
          key-path: '["runs", "using"]'
      
      - name: Run read-yaml action
        id: desc
        uses: ./
        with:
          file: './action.yml'
          key-path: '["output", "data", "description"]'
        
      - name: Get read-yaml outputs
        run: |
          echo '${{ steps.using.outputs.data }}'
          echo '${{ steps.desc.outputs.data }}'
